### ISSUE TITLE
Regular expressions in PrimitiveRuleBindings

### ISSUE THREAD

**Issue by limsbeheer** [duaneedwards/nHapi#1]
Hi!

We found an issue with the regular expressions of the PrimitiveRuleBindings (in class DefaultValidation).
The regular expressions have no matching symbols for the start and ending of the string. This way, too many strings match the regular expressions. By adding the ^ and $ symbols at the beginning and ending of the regexs, only the proper strings are matched.

Thanks!

**Comment by duaneedwards** [comment]
Thanks for reporting this one.

Having a look into it I'm a bit cautious of making a change around these regular expressions just at the moment.

Take for example:

```
IRule number = new RegexPrimitiveRule("(\\+|\\-)?\\d*\\.?\\d*", "");
PrimitiveRuleBindings.Add(new RuleBinding("*", "NM", number));
```

This particular regular expression appears to be trying to enforce that NM results are only numbers ... but since it doesn't have the start and ending anchors as you've pointed out, it will actually match NM results that aren't in fact numbers.

i.e. using the above regular expression to match against value "MoreText", there will be 9 matches.

Likewise for the following, because of no anchors this will basically match everything:

```
IRule nonNegativeInteger = new RegexPrimitiveRule("\\d*", "");
PrimitiveRuleBindings.Add(new RuleBinding("*", "SI", nonNegativeInteger));
```

The reason I'm a bit hesitant about just fixing this one immediately is that there is a very high likelihood this will impact people.  Not in a good way either, DataTypeExceptions  will start getting thrown that people may not have been expecting.

If anything, I'd lean towards removing these regular expressions or making them opt in --not as part of the default validation.

It's a tough call, what are your thoughts?

**Comment by limsbeheer** [comment]
The example you described is exactly what we meant. Just fixing this one, will certainly make people angry, not a good idea ;-)

Our idea is to add an optional boolean parameter to the constructor of the PipeParser (default: false). If set to True, the validation with the more strict regular expressions is added, else the current default validation is used.
Can this be a working solution?

**Comment by duaneedwards** [comment]
As suggested I've now moved out the regular expression field validations into their own new opt-in StrictValidation context, correcting the anchoring tags as you've raised.

There are a few unit tests as well that I've added around the SI / NM number validation, using both the default / strict validation methods now available in the 'ValidationTests' test fixture if you want to see how to use the new strict method -- it's pretty simple really.

I'll upload these changes in a new release later today, but with these changes I consider this issue to be now resolved.
