### ISSUE TITLE
"IN1, IN2, IN1, IN2" results in "IN1, IN2, IN12, IN22"

### ISSUE THREAD

**Issue by taiji123** [duaneedwards/nHapi#14]
When processing this message:

MSH|^~\&|INV|TEST123|FACILITY123|TEST|201503152359||ADT^A08|CHPFQP03|T|2.3
EVN|A08|201503152359
PID|1||30210546||DOE^JOHN^V||19450225|M||1|3001 BLAH RD^APT 430^VOORHEES^NJ^08043||(555)751-1600^PRN^^^^555^7511600|(555)751-1600^OTH^^^^555^7511600||||A1233848515|123-45-6789
PD1|||||||||||
NK1|0001|NAME1^NAME2|O||(555)339-6750^PRN^^^^555^3396750||1
NK1|0002|NOT EMPLOYED|3||||1
PV1|1|I|M^HAHAH^07^3||||035147^CONTTONK ,JOHN J|000000||MED|||||||035147^CONTTONK ,JOHN J|I||P^20150314||||||||||||||||||||||||201503142101
GT1|0001|123562492^^^MFJ^GN|DOE^JOHN^V||3001 BLAH RD^APT 430^VOORHEES^NJ^08043|(555)751-1600^PRN^^^^555^7511600||89450225|||S|123-45-6789||||NOT EMPLOYED
IN1|0001|P02||MEDICARE I/P ONLY|PO BOX 1234^^MECHANICSBURG^PA^123456789||(555)235-8048^PRN^^^^555^2358048|||||||NA|M|DOE^JOHN^V^^^^L|S|19450225|3001 BLAH RD^APT 430^VOORHEES^NJ^08043|||1||||||||HS||||||123562492A|||||||M||N
IN2||123-45-6789|^NOT EMPLOYED^^^^^^^^L||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||(555)751-1600^PRN^^^^555^7511600|||||||NOT EMPLOYED^L||
IN1|0002|Q04|22326|CHARITY 123 HEALTH|CLAIMS PROCESSING DEPT^PO BOX 1234^LONDON^KY^40742||(555)682-9091^PRN^^^^555^6829091|||||||NA|W|DOE^JOHN^V^^^^L|S|12350225|3001 BLAH RD^APT 430^VOORHEES^NJ^08043|||2||||||||HS||||||12302249|||||||M||N
IN2||123-45-6789|^NOT EMPLOYED^^^^^^^^L||||||||||||||||||||||12326||||||||||||||||||||||||||||||||||||||(555)751-1600^PRN^^^^555^7511600|||||||||
ACC|201503141800|I||||

the resulting structure contains segments (note "IN12"):
MSH
EVN
PID
PD1
NK1
NK1
PV1
GT1
IN1
IN2
IN12
IN22
ACC

(All the data inside IN12 and IN22 is valid, following the order in which they appear in the original message.)

The expected structure of the parsed message:

MSH
EVN
PID
PD1
NK1
NK1
PV1
GT1
IN1
IN2
IN1
IN2
ACC

Note that the other repeated segment, NK1, turns out just fine.

Looking through the code trying to figure out what's going on, but just thought I'd mention it.  Will post any findings -- IF I do manage to solve it properly...

**Comment by duaneedwards** [comment]
Hrmm ... I don't seem to be able to see what you are seeing here.

Here's what I did, first I changed the control characters from '^~&' to '^~\&' so that I can encode back to a pipe format from the decoded message.

Then just running:

```
PipeParser parser = new PipeParser();
IMessage m = parser.Parse(message);
var adtA01 = m as ADT_A01;

var insurance1 = adtA01.GetINSURANCE(0); // first insurance group
var insurance2 = adtA01.GetINSURANCE(1); // second insurance group

var pipeDelimitedMessage = parser.Encode(adtA01);
```
And inspecting the results, things seem ok to me... Where are you inspecting such that you can see these IN12 and IN22 segments?

**Comment by taiji123** [comment]
Not sure what you changed the control characters to (both appear identical, '^~&'), but regardless... maybe the encoding process knows how to handle these cases.  Maybe that's why they're named like that, to "group" or "bind" the IN1s with their correspondent IN2s...

Here's how I got to see it, using the debugger (and the message in the OP, without any modification):

`PipeParser parser = new PipeParser();`
followed by:
![image](https://cloud.githubusercontent.com/assets/11446424/6677964/35c75798-cc0b-11e4-9faf-03d986fa9597.png)

Hope that manes sense...

**Comment by taiji123** [comment]
In the meantime I've worked around the issue by truncating all segment names that are longer than 3 characters.  (Did it after the `parser.Parse` call, while processing the parsed results to build our object model -- i.e. outside the core code.)  Not pretty, but it worked.  Just FYI.

**Comment by duaneedwards** [comment]
I changed the control codes to '^~\\&', sorry was an escaping issue with the github markdown it seems.

The insurance related segments do get grouped into the parsed message as they are a repeating group of optional, repeating segments, I think you're right in that the appended numbers are related to the grouping mechanism.

It looks like you are dealing with the abstract / raw base type which is a bit different to using the parsed types.  nHapi sort of prescribes parsing down to a concrete type (one for each event) then walking that object model for what you want to do, something more like this in your case:

```
PipeParser parser = new PipeParser();
IMessage m = parser.Parse(message);
var adtA01 = m as ADT_A01;
for (int index = 0; index < adtA01.INSURANCERepetitionsUsed; index++)
{
	var insuranceGroup = adtA01.GetINSURANCE(index);
	var in1 = insuranceGroup.IN1;
	var in2 = insuranceGroup.IN2;

	// do stuff
}
```

But this isn't ideal in all cases (since you need to code against each *specific* event type, which is why I'm guessing you went with a more generic approach.  One of the shortcomings of this approach to parsing that nHapi uses.

However, it looks like you've got a workaround that will work for you so that's good.
