### ISSUE TITLE
nHapi/NHapi20/NHapi.Model.V251/Datatype/ST.cs incorrect namespace?

### ISSUE THREAD

**Issue by lharless** [duaneedwards/nHapi#20]
I am trying to parse some V251 HL7 OBX lines with a datatype of ST.  These are causing exceptions.  I've narrowed it down to line 164 of 

nHapi/NHapi20/NHapi.Base/Model/Varies.cs

Type c = factory.GetTypeClass(obx2.Value, segment.Message.Version);

This returns null when obx2.Value="ST"

If I change the namespace line in 

nHapi/NHapi20/NHapi.Model.V251/Datatype/ST.cs

to 

namespace NHapi.Model.V251.Datatype

the exceptions go away.

**Comment by duaneedwards** [comment]
Thanks lharless, I've reproduced this and made a fix to resolve this in 35130ef25751236f65c305839d8e0b1f2480e82f.

This has been pushed to nuget.org as a new version v2.4.0.11 now for you to use.

**Comment by lali-nalashaa** [comment]
Hi duaneedwards ,

The issue still exists in nHapi latest version (nHapi 2.5.0.6 (this version)), I tried to parse a sample RSP HL7 message from NIST and get the error.
`
at NHapi.Base.Model.Varies.fixOBX5(ISegment segment, IModelClassFactory factory)
   at NHapi.Base.Parser.PipeParser.Parse(ISegment destination, String segment, EncodingCharacters encodingChars)
   at NHapi.Base.Parser.PipeParser.DoParse(String message, String version)
   at NHapi.Base.Parser.ParserBase.Parse(String message, String version)
   at NHapi.Base.Parser.ParserBase.Parse(String message)`

The line of code which triggered this error was 
`IMessage m = parser.Parse(message.Value);  `

Can you please confirm whether this issue is fixed in latest version? if not please help me in resolving this issue?
