### ISSUE TITLE
No IN1 segments ?

### ISSUE THREAD

**Issue by stephenhauck** [duaneedwards/nHapi#24]
I am parsing a 2.4 message and I try to parse the insurance information and it says it does not exist even though I see it in the message and the object knows about the insurance information because it shows INSURANCERepetitionsUsed = 1.

I try the code below and the the error shown:
NHapi.Model.V24.Segment.IN1 in1 = (NHapi.Model.V24.Segment.IN1)m.GetStructure("IN1");
IN1 does not exist in the group NHapi.Model.V24.Message.ADT_A01

Any ideas ?

**Comment by THEStephenStanton** [comment]
Seams to give the same problems with 2.5 and 2.5.1 messages.

**Comment by duaneedwards** [comment]
This is actually expected behaviour.  The IN1 structure isn't in the ADT_A01 message structure but actually resides in the ADT_A01_INSURANCE group of the ADT_A01 message structure.

ADT_A01:
![image](https://cloud.githubusercontent.com/assets/65170/16865534/d3c91356-4aa8-11e6-82a0-1562ec40148e.png)

ADT_A01_INSURANCE:
![image](https://cloud.githubusercontent.com/assets/65170/16865572/1f6da470-4aa9-11e6-9e5d-c76d08e7b603.png)

The following is a unit test that shows how to access the IN1 segment:
![image](https://cloud.githubusercontent.com/assets/65170/16865645/9bdbb95c-4aa9-11e6-9bfe-9212e41d11d4.png)

**Comment by HMoen** [comment]
Hi @THEStephenStanton, how were you able extract the IN1 segment out of the ORM_001? The Parse method of PipeParser() returns a ORM_001 type immediately instead of an abstract message per nHAPI beginner's guide, thus not allowing casting to ADT_001.

I'm using a HL7 2.5.1 file with VS2017 + nHAPI 2.5.0.6.

Thanks!
