### ISSUE TITLE
"Can't get repetition" errors for PID (possibly other segments too?)

### ISSUE THREAD

**Issue by taiji123** [duaneedwards/nHapi#25]
Running with 2.4.0.11 DLLs, I'm seeing the following behavior:

Test message:
`MSH|^~\&|MILL|EMRY|MQ|EMRY|20150619155451||ADT^A08|Q2043855220T2330403781X928163|P|2.3||||||8859/1`
`EVN|A08|20150619155451`
`PID|1|935307^^^EUH MRN^MRN^EH01|25106376^^^TEC MRN~1781893^^^CLH MRN~935307^^^EUH MRN~5938067^^^EMPI|1167766^^^CPI NBR^^EXTERNAL~90509411^^^HNASYSID~10341880^^^HNASYSID~50627780^^^HNASYSID~5938067^^^MSG_CERNPHR|BUCERO^HERL^CHRISTIN^^^^Cur_Name||19420211|F||WHI|123 PEACHTREE RD^UNIT 123^ATLANTA^GA^30123^USA^HOME^^Fulton||5558609917^HOME~5558609917^CELL~BUCERO@YAHOO.COM^EMAIL|5558609917^BUS|ENG|M|OTH|12345665161^^^EUH FIN^FIN NBR^EH01|123454103|GA123450071||Non-Hispanic|||0|""|""|""||N`

Parsing fails with:
_'Can't get repetition 2 from field 4 - maximum repetitions is only 1 reps.: Segment: PID (rep 0) Field #4'_

When the repetitions are removed from that field:
`MSH|^~\&|MILL|EMRY|MQ|EMRY|20150619155451||ADT^A08|Q2043855220T2330403781X928163|P|2.3||||||8859/1`
`EVN|A08|20150619155451`
`PID|1|935307^^^EUH MRN^MRN^EH01|25106376^^^TEC MRN~1781893^^^CLH MRN~935307^^^EUH MRN~5938067^^^EMPI|1167766^^^CPI NBR^^EXTERNAL|BUCERO^HERL^CHRISTIN^^^^Cur_Name||19420211|F||WHI|123 PEACHTREE RD^UNIT 123^ATLANTA^GA^30123^USA^HOME^^Fulton||5558609917^HOME~5558609917^CELL~BUCERO@YAHOO.COM^EMAIL|5558609917^BUS|ENG|M|OTH|12345665161^^^EUH FIN^FIN NBR^EH01|123454103|GA123450071||Non-Hispanic|||0|""|""|""||N`

-- parsing succeeds.

Fields 3 and 4 both have CX type, so I'm not sure why 4 is having this trouble while 3 doesn't?

Now for the really interesting part: **when I run with DLLs version 2.4.0.0, none of these issues exist!**  Both sample messages above work just fine.

Also noticed the same problems with PID 15 and 22 (I think the errors were that their values were required, whereas according to the HL7 spec they're not) -- there are maybe/probably others having similar issues that I just haven't noticed yet.

Just like with the field 4 error above, the PID 15 and 22 errors also **did not happen when running with 2.4.0.0 version**.

Any ideas or suggestions (aside from "just use the 2.4.0.0 version" :-))?

Thank you!

**Comment by duaneedwards** [comment]
This issue appears to be resolved now that the v23 models have been regenerated from the latest HL7 standards database.  I suspect this was an issue with the HL7 standards database that was used at the time that nHapi was previously generated (before I was involved with the project).

Basically it seems that the fields weren't repeating when they in fact should have been.

Below is the diff of the commit that resolves this issue for this file:
![image](https://cloud.githubusercontent.com/assets/65170/16865142/e457434e-4aa5-11e6-9057-8d450d5e2052.png)

The following unit test works as expected as well:
![image](https://cloud.githubusercontent.com/assets/65170/16865218/5d1411f4-4aa6-11e6-922b-779ecf87f530.png)


The latest release of nHapi (version 2.5+) includes the above change, just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database.

Closing this as I no longer believe that this is an issue with the current version.
