### ISSUE TITLE
v2.5.1 does not support multiple OBX for ORM_O01

### ISSUE THREAD

**Issue by cessationoftime** [duaneedwards/nHapi#26]
The ORM_O01_ORDER_DETAIL class for v2.5.1 is missing OBSERVATIONRepetitionsUsed property and GetOBSERVATION(int rep) method.

OBX should be optional and repeating in v2.5.1 for ORM_O01
[HAPI OBX V2.5.1](http://hl7api.sourceforge.net/v251/apidocs/ca/uhn/hl7v2/model/v251/group/ORM_O01_ORDER_DETAIL.html)

**Comment by duaneedwards** [comment]
This issue appears to be resolved now that the v251 models have been regenerated from the latest HL7 standards database.  I suspect this was an issue with the HL7 standards database that was used at the time that nHapi was previously generated (before I was involved with the project).

Below is the diff of the commit that resolves this issue for this file:

![image](https://cloud.githubusercontent.com/assets/65170/16859709/6fac0d62-4a74-11e6-888b-fd508e412608.png)

The latest release of nHapi (version 2.5+) includes the above change, just be wary there may be some breaking changes due to the structure being regenerated based off a more correct standards database.

Closing this as I no longer believe that this is an issue with the current version.
