### ISSUE TITLE
NHapi.Model.V251 not in NuGet Package 2.4.0.4

### ISSUE THREAD

**Issue by bbunderson** [duaneedwards/nHapi#5]
Is there any reason that the V2.51 model is not in the latest NuGet package?

**Comment by duaneedwards** [comment]
Thank you for reporting this.

The issue was that I created command line targets for packaging and deploying the nuget package, and in the process of doing so mistakingly didn't add the reference for the V2.51 model to get packaged and deployed.

I've since corrected this and pushed a new version to nuget.org which includes the V2.51 model.
