### ISSUE TITLE
2.51 Does Not Support Mutliple OBX for ORU^R01

### ISSUE THREAD

**Issue by bbunderson** [duaneedwards/nHapi#6]
The ORU_R01_ORDER_OBSERVATION class for 2.51 is missing OBSERVATIONRepetitionsUsed property and GetOBSERVATION(int rep) method creating an issue for accessing multiple OBXs. This may be by design, but I am not sure.

**Comment by duaneedwards** [comment]
Thank you for raising this issue.

I've looked over the spec, and it turns out for the ORU_R01 message type with V2.51, not just the observation segment was incorrect, the Timing Quantity and Specimen segments also exhibited the exact same error. (Not repeating when it should have been, marked as a required segment when in fact they are optional).

I've regenerated the ORU_R01 definition for V 2.5.1 using the latest HL7 database definition which resolves all of these, and will push up a new release to nuget later today.
